weights: datasets/noise1.8-rot15/yolov5s.pt
cfg: ''
data: datasets/noise1.8-rot15/data.yaml
hyp:
  lr0: 0.0085808
  lrf: 0.11304
  momentum: 0.90525
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.014756
  hsv_s: 0.042707
  hsv_v: 0.40264
  degrees: 29.223
  translate: 0.21457
  scale: 0.13478
  shear: 5.0942
  perspective: 0.0
  flipud: 0.17488
  fliplr: 0.24741
  mosaic: 0.0
  mixup: 0.51676
  copy_paste: 0.36805
  anchors: 3.0
epochs: 500
batch_size: 40
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: yolov5/data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: datasets/noise1.8-rot15/run2
name: train_results
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 0
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: datasets/noise1.8-rot15/run2/train_results
