weights: datasets/really-big-dataset/yolov5m.pt
cfg: ''
data: datasets/really-big-dataset/data.yaml
hyp:
  lr0: 0.034039
  lrf: 0.011114
  momentum: 0.84583
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.0
  hsv_s: 0.50148
  hsv_v: 0.1478
  degrees: 2.7309
  translate: 0.15478
  scale: 0.36156
  shear: 2.0427
  perspective: 0.00010325
  flipud: 0.0
  fliplr: 0.21058
  mosaic: 0.3015
  mixup: 0.091671
  copy_paste: 0.2051
  anchors: 3.0
epochs: 500
batch_size: 20
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: yolov5/data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: datasets/really-big-dataset/run3
name: train_results
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: datasets/really-big-dataset/run3/train_results
