weights: datasets/benchmark/yolov5n.pt
cfg: ''
data: datasets/benchmark/data.yaml
hyp:
  lr0: 0.035595
  lrf: 0.087253
  momentum: 0.92395
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.023203
  hsv_s: 0.05205
  hsv_v: 0.0
  degrees: 0.16788
  translate: 0.031687
  scale: 0.033109
  shear: 0.015339
  perspective: 0.0
  flipud: 0.027621
  fliplr: 0.078276
  mosaic: 0.0
  mixup: 0.19304
  copy_paste: 0.027662
  anchors: 3.0
epochs: 200
batch_size: 30
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: yolov5/data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: datasets/benchmark/run1
name: train_results
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 30
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: datasets/benchmark/run1/train_results
